### ISSUE TITLE
What is the purpose of bacsec files in bacnet/datalink?

### ISSUE THREAD

**Issue by kaleidoscope-dev** [bacnet-stack/bacnet-stack#465]
I can't find their use anywhere in the stack. I presume they do something with security?

**Comment by skarg** [comment]
The files were used with the BACnet standard defined Clause 24 BACnet Security, which was deprecated when BACnet Secure Connect was published.  I voted to retain Clause 24, but the consensus voted otherwise.  We're still working in committee on providing some kind of link-layer security for Ethernet and MSTP datalinks.
