### ISSUE TITLE
Building shared bacnet-stack libraries using cmake fails + openssl

### ISSUE THREAD

**Issue by madebr** [bacnet-stack/bacnet-stack#49]
Hello,

While helping to package this project at https://github.com/conan-io/conan-center-index/pull/909, I noticed some problems with bacnet-stack.

- When building shared libraries using cmake, the build fails.
I think this is because the linux build has not all files included.
- Also, some files use `OpenSSL`, but the cmake script does not look for it.
It requires a `find_package(OpenSSL)` somewhere + use of the variables/targets.
- macos fails to build

Fixing these issues should also fix some potential problems with the static build.

travis output
https://travis-ci.com/madebr/bacnet-stack/jobs/288603211
changes to `.travis.yml`:
https://github.com/madebr/bacnet-stack/commit/42041220cf1dc864614beadfa1be645b28cde550

**Comment by gocarlos** [comment]
yes, I also realized now that one header of the bacnet-stack has dependencies to openssl...
Though I do not see any other reference to openssl in the old build system e.g. makefile or msbuild... 

@skarg is this code with openssl still supported? e.g. `bacsec_linux.c`

I tried to bring now the openssl dependency to the code to make it compile though the openssl functions are already deprecated since 1.1.0: `HMAC_CTX_init() was replaced with HMAC_CTX_reset() in OpenSSL versions 1.1.0.` https://www.openssl.org/docs/man1.1.0/man3/HMAC.html 
there are some new functions as a drop in placement, other functions were removed and the code has to be adapted or if not needed anymore removed...

**Comment by skarg** [comment]
The recent BACnet/SC addendum also included deprecation of Clause 24 security, so bacsec_linux.c and the openssl dependency will likely be removed.  Technically it can still be used for older protocol-revisions.

**Comment by gocarlos** [comment]
https://github.com/bacnet-stack/bacnet-stack/pull/52 should fix this problem...

only the msvc linker seems to have issues with paths/spaces....

**Comment by madebr** [comment]
@gocarlos I think the error is about a missing implib.
This is because of the same reason as https://github.com/conan-io/conan-center-index/pull/968#issuecomment-591455195.
When no `__declspec(dllexport)` annotations or no `def file` is given, the linker assumes all functions are internal and all are put in the dll.
What `__declspec(dllexport)` does is telling the linker that this function should be visible to users through the implib, which is a `.lib` file (for MSVC, for mingw it is a `.a`).

Check this cmake module out:
https://cmake.org/cmake/help/latest/module/GenerateExportHeader.html

**Comment by gocarlos** [comment]
yeap, lets fix the openssl stuff first, then the shared lib thing...

@skarg do you want to support the bacnet-stack as a shared library under windows?
This would need the exports as @madebr mentioned above

**Comment by skarg** [comment]
I have been building the command line tools under Windows using MinGW, either as archive (static lib) in previous (0.8.x/0.9.x) or as linked objects (0.99.x-->1.0.0).  If a particular Windows build needs the `__declspec(dllexport)` added somewhere for other compilers or build systems, I'm okay with someone adding it as long as it is not breaking the other builds.
