### ISSUE TITLE
Specify pin for DE/RE on a MAX485

### ISSUE THREAD

**Issue by deve87** [bacnet-stack/bacnet-stack#776]
I wanted to test atmega168 port. Compiled OK, but can't understand where to specify the output pins for RE/DE?
I apologize if it's obvious, but I'm not so familiar with C coding.

**Comment by skarg** [comment]
Some things about the atmega168 port:

- I configured the project to use Atmega328 instead of Atmega168 since the code no longer fits into Atmega168 flash space using GCC compiler
- The code does very little - just exposing some I/O as Binary or Analog objects.
- The RS485 abstraction (code) is done in rs485.c module.

The RE/DE is accomplished in ports/atmega168/rs485.c module:
```
void RS485_Transmitter_Enable(bool enable)
{
    if (enable) {
        BIT_SET(PORTD, PD2);
    } else {
        BIT_CLEAR(PORTD, PD2);
    }
}
```

**Comment by deve87** [comment]
Thank you.

I connected the RE/DE to PD2 and seem to work. But can't get the atmega328 to communicate with an Johnson Controls NAE on the MSTP port. The LED's show communicate between, but no device is discovered in J.C.

The correct thing is to change the atmega328 clock speed in hardware.h to 16mhz (F_CPU 16000000UL) and change "RS485_Baud" in rs485.c to 38400 right? Or do I miss something here?
I use an Arduino Uno with the ATmega328 and MAX485 transceiver

**Comment by skarg** [comment]
Thanks for the updates when using the Arduino Uno board with ports/atmega168 example.
I developed the ports/atmega168 example for a board I designed using Atmega168, so that is why the values don't match Arduino Uno.

In ports/atmega168/main.c where the program starts, the baud is set to 38400 via RS485_Set_Baud_Rate(38400); function call. The RS485_Baud in rs485.c module is the default value if not set via the function.

Yes, there could be timing or other issue. I haven't tested with an Arduino Uno Atmega238 and RS485 transceiver yet, but it should be easy to do this.  The timing can be checked with oscilloscope or serial analyzer.

**Comment by deve87** [comment]
Would be great to have a working port for the uno with MSTP some day. Have no experience on how to do so myself, checking for timing issues and so on.

Thanks again for you'r replies.

**Comment by deve87** [comment]
The only problem was I had not set a valid MAC address. So when I connected the Uno to the Johnson Controls NAE with an MAC of 0. The J.C would not establish communication. Simply set MAC to 5 solved the problem. Now able to discover the Uno.

**Comment by deve87** [comment]
> * The code does very little - just exposing some I/O as Binary or Analog objects.

Can I as if the BV or AV object is supposed to change with the atmega I/O pins?
If I change the DDRB = 0 to 1 All the PB port acts as outputs but is it possible to write PV and  then change the these pins to low/ high?

**Comment by deve87** [comment]
Great! Will test this out when I have the time. 
Made some setups with bacpypes and raspberry GPIO over BACnetIP. Would be great using an Uno as well over MSTP with some relays and DI inputs using I/O.

Thanks for replying.
